config/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("posts/", include("posts.urls", namespace="posts")),
]

core/urls.py
from django.urls import path
from posts import views as post_views

app_name = "core"

urlpatterns = [
    path("", post_views.Homeview.as_view(), name="home"),
    path("intro", post_views.intro, name="intro"),
]

posts/urls.py
from django.urls import path
from . import views

app_name = "posts"

urlpatterns = [
    path("<int:pk>/", views.PostDetailView.as_view(), name="detail"),
    path("<int:pk>/delete/", views.DeletePostView.as_view(), name="delete"),
    path("category/<str:category_name>/", views.CategoryView, name="category"),
]

core/models.py
from django.db import models


class TimeStampedModel(models.Model):

    """Time Stapmed Model"""

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

posts/models.py
from django.db import models
from django.urls import reverse
from ckeditor.fields import RichTextField
from core import models as core_models
from users import models as user_models


class Category(core_models.TimeStampedModel):

    """Category Model Definition"""

    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("home")


class Post(core_models.TimeStampedModel):

    """Post Model Definition"""

    category = models.CharField(max_length=30, default="공지사항")
    title = models.CharField(max_length=80)
    writer = models.ForeignKey(user_models.User, on_delete=models.CASCADE, null=True)
    body = RichTextField()
    view_count = models.IntegerField(default=0)

    def __str__(self):
        return self.title[:20]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    pass

core/views.py
from django.shortcuts import render

# Create your views here.

posts/views.py
from django.core import paginator
from django.db import connection, models
from django.http import request
from django.shortcuts import get_object_or_404, redirect, render
from django.urls.base import reverse_lazy
from django.views.generic import ListView, DetailView, DeleteView
from django.core.paginator import Paginator
from . import models


def intro(request):
    return render(request, "posts/intro.html")


class Homeview(ListView):

    model = models.Post
    template_name = "posts/home.html"


def CategoryView(request, category_name):
    page = request.GET.get("page")
    category_posts = models.Post.objects.filter(category=category_name)
    paginator = Paginator(category_posts, 10)
    posts = paginator.get_page(page)
    categories = models.Category.objects.all()
    return render(
        request,
        "posts/categories.html",
        {
            "category_name": category_name,
            "category_posts": category_posts,
            "categories": categories,
            "posts": posts,
        },
    )


class PostDetailView(DetailView):

    model = models.Post
    template_name = "posts/post_detail.html"


class DeletePostView(DeleteView):

    model = models.Post
    template_name = "auth/confirm_delete.html"
    success_url = reverse_lazy("posts:list")

users/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">
    <title>{% block page_title %}{% endblock page_title %} | IEMU11</title>
</head>
<body>
    <header class="w-full h-36">
        {% include 'partials/nav.html' %}
    </header>

    {% block content %}{% endblock content %}

    <footer class="w-full mt-32">
        {% include 'partials/footer.html' %}
    </footer>
</body>
</html>

templates/partials/footer.html
<div class="container w-5/6 mx-auto pt-24 pb-4 flex justify-between border-t border-gray-300">
    <span class="text-sm font-light">© 2021 IEMU11 All rights reserved.</span>
    <ul class="flex flex-row">
        <li class="ml-4"><a href="https://www.facebook.com/IEMU11/" target="_blank" class="text-2xl text-gray-400"><i class="fab fa-facebook-square"></i></a></li>
        <li class="ml-4"><a href="https://www.instagram.com/iemu11/?hl=ko" target="_blank" class="text-2xl text-gray-400"><i class="fab fa-instagram"></i></a></li>
        <li class="ml-4"><a href="https://www.youtube.com/channel/UCpq4QCYACaqv_9m_TO-IkdQ" target="_blank" class="text-2xl text-gray-400"><i class="fab fa-youtube"></i></a></li>
    </ul>
</div>

templates/partials/nav.html
{% load static %}
<div class="flex justify-center mt-5"><a href="{% url 'core:home' %}"><img src="{% static 'img/logo/logo.png' %}" alt="" class="w-28 text-center"></a></div>
<ul class="container w-5/6 mx-auto flex flex-row mt-3">
    <li class="nav-link"><a href="{% url 'core:home' %}">IEMU11</a></li>
    <li class="nav-link"><a href="{% url 'core:intro' %}">소개</a></li>
    <li class="nav-link"><a href="{% url 'posts:category' category_name='공지사항' %}">소식</a></li>
</ul>

templates/posts/categories.html
{% extends 'base.html' %}

{% block page_title %}{{category_name}}{% endblock page_title %}

{% block content %}

<div class="w-full h-64 bg-cover" style="background-image: url(https://igralaxe.sirv.com/WP_www.galahospitality.co.uk/football-hospitality/Spurs-football-hospitality/Tottenham-2019-Getty-Banner-1.jpg);"></div>
<div class="container w-5/6 mx-auto mt-24 flex">

    <div class="w-1/5 mr-28">
        <h1 class="text-xl font-medium mb-5">IEMU11 소식</h1>
        <ul>
            {% for category in categories %}
            <li class="mb-3 font-medium text-base hover:text-blue-800"><a href="{% url 'posts:category' category.name %}">{{category.name}}</a></li>
            {% endfor %}
        </ul>
    </div>
    
    <div class="w-4/5">
        <h1 class="text-xl font-medium mb-5 text-left block w-full">{{category_name}}</h1>
        {% for post in posts %}
            <div class="w-full h-20 border-t border-b border-gray-300 my-3">
                <ul>
                    <li>{{post.title}}</li>
                    <li><a href="{% url 'posts:detail' post.pk %}">보기</a></li>
                </ul>
            </div>
        {% endfor %}

        <div class="w-full flex justify-center text-lg mt-10">
            {% if posts.has_previous %}
            <a href="?page={{posts.previous_page_number}}" class="mr-3 hover:text-blue-600"><i class="fas fa-angle-double-left"></i></a>
            {% endif %}

            {% for p in posts.paginator.page_range %}
                <a href="?page={{p}}" class="mx-1">{{p}}</a>
            {% endfor %}
            
            {% if posts.has_next %}
                <a href="?page={{posts.next_page_number}}" class="ml-3 hover:text-blue-600"><i class="fas fa-angle-double-right"></i></a>
            {% endif %}
        </div>
    </div>
</div>

{% endblock content %}

templates/posts/home.html
{% extends 'base.html' %}

{% block page_title %}Home{% endblock page_title %}

{% block content %}

<div class="w-full h-96 bg-center bg-cover mb-10" style="background-image: url(https://www.p1travel.com/wp-content/uploads/2021/06/2021-2022-5-scaled.jpg);"></div>

<div class="container w-5/6 mx-auto">
    

    <iframe width="480" height="270" src="https://www.youtube.com/embed/w-mSE58Zofc" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>

{% endblock content %}

templates/posts/intro.html
{% extends 'base.html' %}

{% block page_title %}Intro{% endblock page_title %}

{% block content %}

<div class="w-full h-64 bg-cover" style="background-image: url(https://igralaxe.sirv.com/WP_www.galahospitality.co.uk/football-hospitality/Spurs-football-hospitality/Tottenham-2019-Getty-Banner-1.jpg);"></div>
<div class="container w-5/6 mx-auto pt-24 flex">

    INTRO
</div>

{% endblock content %}

templates/posts/post_detail.html
{% extends 'base.html' %}

{% block page_title %}{{post.title}}{% endblock page_title %}

{% block content %}

<div class="w-full h-64 bg-cover" style="background-image: url(https://igralaxe.sirv.com/WP_www.galahospitality.co.uk/football-hospitality/Spurs-football-hospitality/Tottenham-2019-Getty-Banner-1.jpg);"></div>
<div class="container w-5/6 mx-auto mt-24">
    <div>
        <h1 class="font-bold text-2xl mb-10 border-b border-gray-300 pb-4">{{post.title}}</h1>
        {{post.created|date:"F-j-o"}}
        {{post.category}}
        {{post.writer}}
    </div>

        {{post.body}}
        {% if user.is_authenticated %}
        <a href="{% url 'posts:delete' post.pk %}">삭제</a>
        {% endif %}
</div>        
{% endblock content %}